# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - main
  
pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    steps:
    - task: GoTool@0
      inputs:
        version: '1.19'
        
    - task: Go@0
      inputs:
        command: custom
        customCommand: 'mod'
        arguments: 'tidy'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Go mod tidy'

    - task: Go@0
      inputs:
        command: 'custom'
        customCommand: 'get'
        arguments: 'github.com/revel/cmd/revel'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Go build'
      
    - script: |
        find /* -type d -name revel
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: "Find Revel"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    environment: '$(webAppName)'
    strategy:
      runOnce:
        deploy:
          steps:
            # TBD
            # need to see if it's possible to use a typical deploy task or deploy via the CLI due to possible Oryx limitations
            # az webapp deploy --resource-group <group-name> --name <app-name> --src-path <zip-package-path>
      
  